backend:
  name: git-gateway
  branch: main
  endpoint: https://blog-gateway.woliaozhijun.workers.dev/gateway

media_folder: "source/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - label: "分类"
        name: "categories"
        widget: "list"
        field: { label: "分类名", name: "category", widget: "string" }
        default: ["随笔"]
      - label: "标签"
        name: "tags"
        widget: "list"
        field: { label: "标签名", name: "tag", widget: "string" }
        default: []
      - { label: "摘要", name: "description", widget: "text", required: false }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "pages"
    label: "页面"
    files:
      - file: "source/about/index.md"
        label: "关于"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "日期", name: "date", widget: "datetime" }
          - { label: "正文", name: "body", widget: "markdown" }
